name: Cache Demo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: prime-cache-4a2d804
        id: prime-cache-4a2d804
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: cache-4a2d804

      - name: Echo cache hit/miss
        run: |
          if [ "${{ steps.prime-cache-4a2d804.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
